### ISSUE TITLE
extra args to ping people

### ISSUE THREAD

**Issue by l4zs** [bankobotv14/BankoBot#60]
it would be nice if you could do like `xd docs spigot Player`
and the bot would respond with `@` the given user.
That would make things easier as the person would know that this command executed by me is an answer to his question.

**Comment by l4zs** [comment]
I mean xd docs spigot Player l4zs
somehow it just removed my name

**Comment by DRSchlaubi** [comment]
sounds great but @warriorzz when you're implementing this make sure to set allowedMentions so you can't ping @everyone

**Comment by l4zs** [comment]
donk

**Comment by NyCodeGHG** [comment]
@warriorzz is very lazy
